from typing import TypedDict, List, Dict, Any

class RAGState(TypedDict, total=False):
    """
    LangGraph State definition for the RAG pipeline.

    Attributes:
        query: User question string.
        context: List of retrieved text/table chunk strings.
        answer: Final answer generated by LLM.
        token_usage: Dict containing input_tokens, output_tokens, total_tokens.
        source_chunks: List of retrieved chunk IDs.
        chunks_details: List of dicts containing detailed chunk information.
    """
    query: str
    context: List[str]
    answer: str
    token_usage: Dict[str, Any]
    source_chunks: List[str]
    chunks_details: List[Dict[str, Any]]


